---
output:
  word_document: default
  html_document: default
---
### Erica MacBride
### Dr. Hill, BAN 502
### Module 3 Assignment 1

```{r}
library(tidyverse)
library(tidymodels)
library(glmnet) 
library(GGally)
library(ggcorrplot)
library(lmtest)
library(car)
library(lubridate)
```
```{r}
bike<- read_csv("bike_cleaned-2.csv")
bike = bike %>% mutate(dteday = mdy(dteday))
bike = bike %>% mutate_if(is.character, as.factor)
bike = bike %>% mutate(hr = as_factor(hr))
```
## Task 1
```{r}
set.seed(1234)
bike_split = initial_split(bike, prob = 0.70, strata = count)
train = training(bike_split)
test = testing(bike_split)
```

## Task 2
There are 13,036 rows in the training set. There are 4343 rows in the testing set.  

## Task 3
```{r}
bike_recipe = recipe(count ~ season + mnth + hr + holiday + weekday + temp + weathersit, train)

lm_model = #give the model type a name 
  linear_reg() %>% #specify that we are doing linear regression
  set_engine("lm") #specify the specify type of linear tool we want to use 

lm_wflow = 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(bike_recipe)

lm_fit = fit(lm_wflow, train)
#summary(lm_fit$fit$fit$fit)
```
The adjusted R-squared value is .62.  

## Task 4
```{r}
predict_train = predict(lm_fit, train)
ggplot(predict_train, aes (x = .pred)) + geom_histogram() + theme_bw()
```

## Task 5
```{r}
lm_fit %>% predict(test) %>% bind_cols(test) %>% metrics(truth = count, estimate = .pred)
```
The R squared value is the same on the testing set as on the training set. 

